version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./volumes/grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Change this to set your Grafana admin password
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Change this to set your MySQL root password
      MYSQL_DATABASE: your_database     # Change this to set your MySQL database name
      MYSQL_USER: your_username         # Change this to set your MySQL username
      MYSQL_PASSWORD: your_password     # Change this to set your MySQL password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
  grafana_data:
    driver: local
